config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'instructions#index'
  resources :instructions do
    resources :steps do
      resource :step_statistic
      get :understand, on: :member
    end
    get :statistic, on: :member
  end

  resource :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_source, ImageUploader

  belongs_to :step
  validates :image_source, presence: true
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :steps

  belongs_to :user
  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :steps, :reject_if => :all_blank, :allow_destroy => true

  validates :title, presence: true
  validates :description, presence: true

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/models/step.rb
class Step < ActiveRecord::Base

  TYPE_MAPPER = { Video: :video, Image: :image, Text: :text}

  belongs_to :instruction

  has_many :videos
  has_many :images
  has_many :texts

  has_one :step_statistic

  accepts_nested_attributes_for :videos, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :texts, :reject_if => :all_blank, :allow_destroy => true

  after_create :create_step_statistic

  mount_uploader :image, ImageUploader

  def sorted_attachments
    attachments = videos.to_a | images.to_a | texts.to_a
    attachments = attachments.sort_by { |obj| obj.position }
    result = []
    attachments.each do |a|
      result << { type: TYPE_MAPPER[a.class.name.to_sym], data: a.to_json }
    end
    result
  end

  def create_step_statistic
    self.step_statistic = StepStatistic.create!(step: self)
  end

end

app/models/step_statistic.rb
class StepStatistic < ActiveRecord::Base

  belongs_to :step

end

app/models/text.rb
class Text < ActiveRecord::Base

  belongs_to :step

  validates :text_description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :instructions
end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :step

  validates :video_source, presence: true

  after_save :normalize_link

  def normalize_link
    normalized_link = "//www.youtube.com/embed/#{video_source.partition('=').last}"
    self.update_column(:video_source, "//www.youtube.com/embed/#{video_source.partition('=').last}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @instructions = current_user.instructions
  end

  def new
    @instruction = Instruction.new
    respond_to do |format|
      format.html
      format.json { render json: @instruction.to_json }
    end
  end

  def show
    @instruction = Instruction.friendly.find(params[:id])
    if current_user && current_user == @instruction.user ||
      params[:token] == @instruction.token
        @steps = @instruction.steps
    else
      redirect_to instructions_path
    end
  end

  def create
    @instruction = Instruction.new(instruction_params)
    @instruction.user = current_user
    @instruction.token = SecureRandom.hex
    @instruction.save
    redirect_to instruction_path(@instruction)
  end

  def statistic
    instruction = Instruction.friendly.find(params[:id])
    @steps = instruction.steps
  end

  private

  def instruction_params
    params.require(:instruction).permit(:title, :description, :image,
      steps_attributes: [:id, :title, :image, :description,
        videos_attributes: [:id, :video_source],
        texts_attributes: [:id, :text_description],
        images_attributes: [:id, :image_source]
      ]
    )
  end
end

app/controllers/step_statistics_controller.rb
class StepStatisticsController < ApplicationController

  def show
    step = Step.find(params[:step_id])
    render json: step.step_statistic.to_json
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def show
    @step = Step.find(params[:id])
    step_statistic = @step.step_statistic
    step_statistic.viewed_count += 1
    step_statistic.save
    render nothing: true, status: 200
  end

  def understand
    step = Step.find(params[:id])
    step_statistic = @step.step_statistic
    step_statistic.understand_count += 1
    step_statistic.save
    render nothing: true, status: 200
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update_attributes(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/step_statistics_helper.rb
module StepStatisticsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/instructions/_image_fields.haml
.nested-fields
  = f.input :image_description
  = f.input :image_source, as: :file
  = link_to_remove_association "remove image", f

app/views/instructions/_step_fields.haml
.icon-block.arrow-up
.container.create-instruction-body
  .add-media-block.step-media-block
    .frame-body.step_image_file
      .upload-preview
      %span.previewTitle
        Выберите изображение инструкции
  %div{style: 'display: none'}
    = f.file_field :image, class: 'step-file-field'
  .add-text-block
    %h2 Шаг
    = f.text_field :title, :placeholder => "Название вашего шага"
    %h2 Дополнительное описание к шагу
    = f.text_area :description, :placeholder => "Краткое описание шага инструкции", :rows => "3"

-# .nested-fields
-#   = f.input :title
-#   #videos
-#     = f.simple_fields_for :videos do |video|
-#       = render 'video_fields', :f => video
-#     .links
-#       = link_to_add_association 'add video', f, :videos
-#   #images
-#     = f.simple_fields_for :images do |image|
-#       = render 'image_fields', :f => image
-#     .links
-#       = link_to_add_association 'add image', f, :images
-#   #texts
-#     = f.simple_fields_for :texts do |text|
-#       = render 'text_fields', :f => text
-#     .links
-#       = link_to_add_association 'add text', f, :texts
-#   = link_to_remove_association "remove step", f

app/views/instructions/_text_fields.haml
.nested-fields
  = f.input :text_description
  = link_to_remove_association "remove text", f

app/views/instructions/_video_fields.haml
.nested-fields
  = f.input :video_source
  = link_to_remove_association "remove video", f

app/views/instructions/index.haml
%h1 Instructions
%ul#selector
  - @instructions.each do |instruction|
    %li
      = link_to instruction.title, instruction_path(instruction)

app/views/instructions/new.haml
= form_for @instruction do |f|
  .container-instruction
    .container.create-instruction-body
      .add-media-block
        .frame-body#instruction_image_file
          .upload-preview
          %span.previewTitle
            Выберите изображение инструкции
      %div{style: 'display: none'}
        = f.file_field :image, id: 'instruction-file-field'
      .add-text-block
        %h2 Инструкция
        = f.text_field :title, :placeholder => "Название вашей инструкции"
        %h2 Дополнительно (не рекомендуется)
        = f.text_area :description, :placeholder => "Краткое описание инструкции", :rows => "3"
      = f.simple_fields_for :steps do |step|
        = render 'step_fields', :f => step
      .links
        = link_to_add_association '#', f, :steps, class: 'icon-block add-instruction-body add-new-step-linkening'
  -# %h3 Steps
  -# #steps
  -#   = f.simple_fields_for :steps do |step|
  -#     = render 'step_fields', :f => step
  -#   .links
  -#     = link_to_add_association '', f, :steps
  
= content_for :instruction_statistic_share do
  = link_to 'Сохранить', 'javascript:void(0)', class: 'common-button-large common-button-large-no-fill', id: 'create_instruction'

app/views/instructions/show.haml
= content_for :instruction_statistic do
  = link_to 'Статистика', statistic_instruction_path(@instruction), class: 'common-link'
= content_for :instruction_statistic_share do
  = link_to 'Поделиться', '#', class: 'common-button-large common-button-large-no-fill', 'data-toggle' => 'modal', 'data-target' => '#share_link_modal'
  .modal.fade#share_link_modal{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog.modal-sm-4
      .modal-content
        .modal-body
          .form-group
            %input.form-control{ type: 'text', value: instruction_url(@instruction, token: @instruction.token) }

.view-container-instruction
  - @steps.each_with_index do |step, i|
    .instruction-body
      .media-block
        = image_tag(step.image)
      .add-text-block
        %h2= step.title
        %p= step.description
    - if i+1 < @steps.count
      .icon-block.arrow-up.revers{ role: 'step', data: { step: i, url: instruction_step_path(@instruction, step) }}

app/views/instructions/statistic.haml
.statistic-table
  .statistic-table-title.text-center
    Статистика качества просмотра
    = link_to 'инструкции', instructions_path(@instruction), class: 'link-to-instruction'
  %table.table.statistic-table-data
    %tr.active
      %th.col-sm-3
      %th.col-sm-3.text-center Просмотров
      %th.col-sm-3.text-center Успешно просмотренных
      %th.col-sm-3.text-center Коэффициент доступности карточки
    - @steps.each_with_index do |step, i|
      %tr
        - viewed_count = step.step_statistic.viewed_count
        - understand_count = step.step_statistic.understand_count
        %th.text-center
          = "Карточка #{i+1}"
        %td.text-center
          = viewed_count
          - if i > 0
            - previous_viewed_count = @steps[i-1].step_statistic.viewed_count
            - diff_count = previous_viewed_count - viewed_count
            - if previous_viewed_count != 0 && diff_count > 0
              - percent = 100*diff_count/previous_viewed_count
              %span.text-danger= "(-#{percent}%)"
        %td.text-center
          = understand_count
        %td.text-center
          = "#{100*understand_count/viewed_count}%" if viewed_count != 0

app/views/layouts/application.haml
!!!
%html
  %head
    %title InteractiveInstructions
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if current_user || params[:token].present?
      %nav.navigation-pane#navigation-pane.navigation-fixed
        .navigation-left-wrapper
          .navigation-logo
        - if content_for?(:instruction_statistic_share) && current_user
          = yield(:instruction_statistic_share)
        - unless params[:token].present?
          .navigation-user-actions
            - if current_user
              - if content_for?(:instruction_statistic)
                = yield(:instruction_statistic)
              = link_to 'Выйти', destroy_user_session_path, class: 'common-link', method: :delete
            - else
              = link_to 'Войти', new_user_session_path, class: "common-link"
    - else
      .navigation-container
        .enter-registration-header
          .quick-start-block
            .header-logo-container
              = image_tag('logo-with-text.png', class: "logo-with-text")
            %p.attention-text
              Начните создавать
              %br/
              простые и
              %span.text-important понятные инструкции
              %br/
              прямо сейчас
            = link_to 'Создать инструкцию', new_instruction_path, class: 'common-button-large'
        %nav.navigation-pane#navigation-pane
          .navigation-left-wrapper
            .navigation-logo
            %ul.nav-links
          .navigation-user-actions
            - if current_user
              - if content_for?(:instruction_statistic)
                = yield(:instruction_statistic)
              = link_to 'Выйти', destroy_user_session_path, class: 'common-link', method: :delete
            - else
              = link_to 'Войти', new_user_session_path, class: "common-link"
    .main-container#container-base
      = yield

app/views/users/edit.haml
= simple_form_for @user do |f|
  = f.input :first_name
  = f.input :last_name
  = f.submit

app/views/users/show.haml
%h1
  = @user.email
%p
  %strong Имя:
  = @user.first_name
%p
  %strong Фамилия:
  = @user.last_name
%p= link_to 'Редактировать', edit_user_path
%p= link_to 'Сменить email/пароль', edit_user_registration_path